---
name: tf-checks

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    paths:
      - '**/*.tf'
      - '*.tf'
jobs:
  tf-checks-basic-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@v2
    with:
      working_directory: './examples/basic/'
      provider: none
  tf-checks-complete-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@v2
    with:
      working_directory: './examples/complete/'
      provider: none
...